# This is a basic workflow to help you get started with Actions
name: Share data between jobs 
on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - run: echo "Hello World Cem" > file.txt
      - uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt
  job_2:
      name: Download File
      runs-on: ubuntu-latest
      needs: job_1
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: file
        - run: cat file.txt
